name: Gitleaks PR Secret Scan

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    uses: clouddrove/github-shared-workflows/.github/workflows/gitleaks-pr-scan.yml@7bc2965ff8f6b68db9402316dd5dd7498ec9c0e4 # pinned to latest
    secrets: inherit
