name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@1c43f71cb95be532a4ee848596eb73953dde517c
    with:
      provider: digitalocean
      working_directory: ./_examples/basic/

  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@1c43f71cb95be532a4ee848596eb73953dde517c
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/
