name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr_checks.yml@1c43f71cb95be532a4ee848596eb73953dde517c # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
