name: PR Validation

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@61a4d250f08b1e4dd29c61bb8a73eaf9dd0f2a8f # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'
